/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author MSI CYBORG
 */
public class splash_Window extends javax.swing.JFrame {

    /**
     * Creates new form splash_Window
     */
    public splash_Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loadingbar = new javax.swing.JProgressBar();
        valuelo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lolabelside = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(19, 40, 126));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sg (2).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ch/ Sugathananda National Collage");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SDBMS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        loadingbar.setBackground(new java.awt.Color(19, 34, 145));
        loadingbar.setForeground(new java.awt.Color(204, 204, 204));
        loadingbar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        loadingbar.setBorderPainted(false);
        loadingbar.setOpaque(true);
        jPanel1.add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 415, 730, 10));

        valuelo.setFont(new java.awt.Font("Tw Cen MT", 2, 13)); // NOI18N
        valuelo.setForeground(new java.awt.Color(255, 255, 255));
        valuelo.setText("0%");
        jPanel1.add(valuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(195, 195, 195));
        jLabel4.setText("Powerd by ONE_Tera");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        lolabelside.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lolabelside.setForeground(new java.awt.Color(255, 255, 255));
        lolabelside.setText("Loding...");
        jPanel1.add(lolabelside, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(195, 195, 195));
        jLabel5.setText("Version 1.0");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(710, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        splash_Window win1 = new splash_Window();
        win1.setVisible(true);
        
        login lo = new login();
        try {
            for (int i = 0; i < 100; i++) {
                Thread.sleep(70);
                win1.loadingbar.setValue(i);
                win1.valuelo.setText(Integer.toString(i)+"%");
                if(30>i){
                    win1.lolabelside.setText("Loding...");
                    
                }
                else{
                    if(40>i){
                        win1.lolabelside.setText("Copying files..");
                        Thread.sleep(0);
                    }else{
                        if(60>i){
                                win1.lolabelside.setText("Connecting to database...");
                                Thread.sleep(0);
                            }else{
                            if(90>i){
                                win1.lolabelside.setText("Ready.");
                                Thread.sleep(30);
                                win1.lolabelside.setText("Ready..");
                                Thread.sleep(10);
                                win1.lolabelside.setText("Ready...");
                                
                                
                            }
                        }
                    }
                }
                
                
            }
        } catch (Exception e) {
        }
        win1.setVisible(false);
        lo.setVisible(true);
        
        win1.dispose();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar loadingbar;
    private javax.swing.JLabel lolabelside;
    private javax.swing.JLabel valuelo;
    // End of variables declaration//GEN-END:variables
}
